### ISSUE TITLE
Highlighting of a diff from a patch/diff file

### ISSUE THREAD

**Issue by xVermillionx** [the-mikedavis/tree-sitter-diff#2] opened 2022-11-07 16:19 UTC
When creating a diff from a patch/diff file results in the line with additions to the patchfile being recognized as context instead of addition.

**Comment by the-mikedavis** [comment] 2022-11-07 16:48
Duplicate of https://github.com/the-mikedavis/tree-sitter-diff/issues/1

This grammar focuses only on diff syntax: a separate tree-sitter-patch should be created to handle patch syntax and it can inject this grammar for the diff parts

**Closed as not planned by the-mikedavis** 2022-11-07 16:48 UTC
